[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "flask-cors>=6.0.0",
    "flask>=3.1.1",
    "openai>=1.79.0",
    "flask-limiter>=3.12",
    "stripe>=12.1.0",
]
